<div class="switcher store switcher-store" id="switcher-store">
    <strong class="label switcher-label"><span><?= $block->escapeHtml(__('Select Language')) ?></span></strong>
    <div class="actions dropdown options switcher-options">
		<?php foreach ($block->getWebsites() as $_website): ?>
	        <?php if ($_website['id'] == $block->getCurrentStoreId()): ?>
                <div class="action toggle"
                     role="button"
                     tabindex="0"
                     data-mage-init='{"dropdown":{}}'
                     id="switcher-store-trigger">
                    <strong>
                        <span><?= $block->escapeHtml($_website['name']) ?></span>
                    </strong>
                </div>
			<?php endif; ?>
		<?php endforeach; ?>
        <ul class="dropdown switcher-dropdown" data-target="dropdown">
			<?php foreach ($block->getWebsites() as $_website): ?>
	            <?php if ($_website['id'] != $block->getCurrentStoreId()): ?>
                    <li class="switcher-option">
                        <a href="#" data-path="<?php echo $_website['url'] ?>" data-code="<?php echo $_website['code'] ?>"><?= $block->escapeHtml($_website['name']) ?></a>
                    </li>
				<?php endif; ?>
			<?php endforeach; ?>
        </ul>
    </div>
</div>

<script>
  require([
    'jquery',
    'mage/cookies'
  ], function ($) {
        var websiteCodes = <?php echo $block->getWebsiteCodesJson() ?>;
        $('.switcher-option a').on('click', function(e) {
          e.preventDefault();
          var $option = $(this);
          var pattern;
          var urlRoot = $option.attr('data-path');
          var urlPath = String(location.pathname);
          var urlParam = location.search;

          $.cookie('country', $option.attr('data-code'), {path: '/', domain: '<?= $_SERVER['HTTP_HOST'] ?>'});
          for(var locationKey in websiteCodes) {
            pattern = pattern = new RegExp('^\/'+websiteCodes[locationKey]);
            if(pattern.test(urlPath)) {
              urlPath = urlPath.replace(pattern, '');
              break;
            }
          }
          window.location.replace(urlRoot + urlPath + urlParam);
        })
  })
</script>